### ISSUE TITLE
能否增加一个修改标签名的功能

### ISSUE THREAD

**Issue by baiheyyds** [Ziqing19/LabelPixivBookmarks#12]
感谢大佬的脚本，真的很便利！
提一个修改标签名的小功能，这个感觉应该还是很需要的，大佬看下是否有可能实现

1、在编辑词典页面增加修改标签名（目标标签|大标签）的选项
2、在修改词典中标签名后，收藏夹里原标签名替换成新标签名

现在要想修改原标签名只能在收藏夹里边修改原标签，然后还得导出词典修改json文件将目标标签名改成和收藏夹一样的名字。

**Comment by Ziqing19** [comment]
可以的 这个不难做 近期更新

**Comment by baiheyyds** [comment]
o(￣▽￣)ｄ good，感谢大佬回复！期待更新！

**Comment by baiheyyds** [comment]
大佬，我发现现在的AI生成图太热门了，而且它跟R18一样都自带一个官方标签，我就想着是不是能像R18、SFW一样专门筛选出来

**Comment by Ziqing19** [comment]
好像确实可以 正好更新的差不多了 我看下AI这部分有没有什么可以操作的

**Comment by baiheyyds** [comment]
感谢大佬的脚本更新！我运行了一下新的脚本，发现好像存在一点问题，就是修改标签名后，原标签名里的某些作品突然就丢失标签了（旧标签），有的严重的甚至全部标签都丢失，造成了新标签名一个作品都没有，只在词典更新了的情况

**Comment by Ziqing19** [comment]
我测试的时候好像没遇到这样的问题，你的收藏夹公开类型选择对了吗（公开/不公开）
![image](https://user-images.githubusercontent.com/44974769/211097227-3459b18a-8a47-45c5-95f7-acb93f3cb695.png)
比如你选了公开收藏夹，那私密收藏夹里的作品不会更新。

目前流程是：
选择公开类型，选择标签名=》获取需要修改的作品列表=》对这些作品添加新的标签，删除旧标签=》可选地更新词典
这个流程应该和你说的是差不多的，我不是很清楚你说的VSCODE修改是什么

你可以弄一些测试用的图片，然后截图一下修改标签名前后出问题的情况，这样更容易理解
我今天也自己再测试下

**Comment by baiheyyds** [comment]
我测试了一下，这种情况貌似对于囊括作品较小的标签（≤150）不会有任何问题，但是对于囊括作品较多的标签就会出现上述这种标签缺失的情况

**Comment by baiheyyds** [comment]
![QQ截图20230107211759](https://user-images.githubusercontent.com/93436777/211152670-b3fdb566-8b3c-4085-a216-271b69c83f69.png)

就像上图那样，自动标签范围选择全部，以免有漏网之鱼

**Comment by Ziqing19** [comment]
我试了一次性重命名1000以上的收藏，依然没遇到遗漏的情况，有点搞不懂了
不过我发现官方本来就提供了重命名标签的功能，我直接拿来用了
缺点是没法区分公开和非公开作品，两边的标签都会被更新

**Comment by baiheyyds** [comment]
感谢更新，新的脚本运行完美！我的意思就是调用官方的接口，这样消耗的性能也更小。
我觉得一般人公开作品跟非公开作品的标签也不会专门弄成不同的，都是一致的。

**Comment by Ziqing19** [comment]
ok 其实之前用的也是官方另外的接口 不过不是专门重命名标签用的 效率低一些
没问题的话明天我就把这个issue结了

**Comment by baiheyyds** [comment]
没问题了，辛苦大大了！
