### ISSUE TITLE
获取tags失败     Fail to fetch user tags

### ISSUE THREAD

**Issue by dwcjgh** [Ziqing19/LabelPixivBookmarks#13]
脚本版本：@version      2.0
报错提示：获取tags失败       Fail to fetch user tags
网址格式：https://www.pixiv.net/users/********/bookmarks/artworks?rest=hide
浏览器：Firefox 国内版

控制台输出：
![issiue2](https://user-images.githubusercontent.com/78130158/212863520-1c5e01d8-8500-4016-9252-136be638b1a4.png)

参考 issue #2 ：
使用网址 https://www.pixiv.net/ajax/user/********/bookmarks/tags 显示以下内容：
   {"error":true,"message":"\u65e0\u6cd5\u627e\u5230\u60a8\u6240\u8bf7\u6c42\u7684\u9875\u9762","body":[]}
   "无法找到您所请求的页面"

**Comment by Ziqing19** [comment]
抱歉最近没咋看这边，看了下截图是没获取到你的uid
我用的是hack react组件的方式获取的uid，你可以试下console里输入这段看能不能获取到信息
`pageInfo = Object.values(document.querySelector(".sc-x1dm5r-0"))[0][
      "return"
    ]["return"]["memoizedProps"]`
有一种可能是你的`.sc-x1dm5r-0`这个元素被adblock之类的屏蔽了？
如果不行的话尝试下`window.dataLayer[0].user_id`能不能获取到你的uid
