### ISSUE TITLE
[bug] 其他功能中的“更新词典”似乎无效

### ISSUE THREAD

**Issue by Nachogao** [Ziqing19/LabelPixivBookmarks#14]
我在使用“其他功能”中的更改标签功能时，顺带勾选“更新词典”，但我检查了词典，并没有添加对应的标签关系。

**Comment by Ziqing19** [comment]
抱歉这么晚回复。
更新词典功能并不会添加新的标签对，而是更新已有的标签名。
例如原来词典中有foo => bar，在更改标签时更新成foo_1，那么词典中会变成foo_1 => bar

**Comment by Nachogao** [comment]
原来如此，多谢回复
