### ISSUE TITLE
Label Bookmarks does not run when synonyms are defined

### ISSUE THREAD

**Issue by dxman** [Ziqing19/LabelPixivBookmarks#15]
When I click the Start button to apply labels, if the synonym dictionary contains any entries, progress is freezes on the following message and never progresses:

![pixiv-1](https://github.com/Ziqing19/LabelPixivBookmarks/assets/10678981/d17b750a-3d7e-46d8-b228-40453a3ff586)

I opened DevTools to look for any errors, and this is what was displayed:

![pixiv-2](https://github.com/Ziqing19/LabelPixivBookmarks/assets/10678981/2e738978-6b0e-4f09-b297-92933eb25724)

I have read issue #10, which describes similar behavior. Following the suggestion there, I exported my labels and examined the JSON, but there were no nulls or any other corrupt values. I removed all synonyms from the dictionary, tried running again, and it ran successfully. When I attempted to re-add the synonyms one at a time, the error returned immediately.

I am running v5.6 of the script using Violentmonkey in Vivaldi.

**Comment by Ziqing19** [comment]
I am really sorry for the late response.
According to your description, I am wondering that whether the `toUpperCase` method is defined. As this method is added to Array prototype, there is a possibility that the prototype is protected.

Could you please try `["abc"].toUpperCase()` and see if it works?

**Comment by dxman** [comment]
Not a problem, sorry for my late response as well. I believe that your diagnosis is correct.

I quickly ran the above line using VS Code's code runner and received the following output:

![2023-06-26 16_43_58-Window](https://github.com/Ziqing19/LabelPixivBookmarks/assets/10678981/48a851be-70fb-442c-999e-87ef4f653e0c)

Removing the array and running `toUpperCase` against the string itself runs without error:

![2023-06-26 16_48_34-Window](https://github.com/Ziqing19/LabelPixivBookmarks/assets/10678981/00a67c61-7299-426e-8631-958f6f344605)

I think what you'll probably have to do is use `map` to apply `toUpperCase` to each string within the array, like so:

![2023-06-26 16_51_31-Window](https://github.com/Ziqing19/LabelPixivBookmarks/assets/10678981/16b7cf24-d481-4865-a249-6cac1af852f1)

**Comment by Ziqing19** [comment]
Has the environment that you ran the code connected to your browser and loaded the script?
It should be ran in the browser console like this:
![image](https://github.com/Ziqing19/LabelPixivBookmarks/assets/44974769/e9eebfa3-a469-47eb-a925-194d69fe63fd)

**Comment by dxman** [comment]
Here is the example when run from the dev tools console:

![2023-06-26 19_30_15-Window](https://github.com/Ziqing19/LabelPixivBookmarks/assets/10678981/00c24421-cb85-4ded-b04e-80e2d754eea4)

For reference, my version of Vivaldi is 6.1.3035.100, and I am using v2.14.0 of the Violentmonkey extension.

**Comment by Ziqing19** [comment]
It seems that the Array prototype was not updated with the toUpperCase method. Maybe it's protected or not supported by your browser.
Could you please try this snippet in the browser console and I could decide how to make a polyfill then.
`
Array.prototype.toUpperCase = function () {
  return this.map((i) => i.toUpperCase());
};
["abc"].toUpperCase()
`

![image](https://github.com/Ziqing19/LabelPixivBookmarks/assets/44974769/0a4c0fdb-29f8-4bdc-9497-14aea2e604b4)

**Comment by dxman** [comment]
That worked:

![2023-06-27 00_45_36-Developer Tools - Vivaldi - https___www pixiv net_en_ - Vivaldi](https://github.com/Ziqing19/LabelPixivBookmarks/assets/10678981/9406b6f1-e670-4bef-b91c-d38d50d4dfb7)

**Comment by Ziqing19** [comment]
Well it's hard to know what went wrong now...maybe because of your script manager (I used Tampermonkey to develop)
Just to make sure. The script fails once you add any key-value pair to the dictionary, and could work when the dictionary is empty. Is it right?
If so, I will try to increase the robustness of the script later without figuring out the exact bug then...

**Comment by Ziqing19** [comment]
I uploaded a new version with toUpperCase method replaced by a new function. Please take a try and see if it works for you.

**Comment by dxman** [comment]
I just ran a few tests, and everything appears to be working. If I run across anything else, I'll let you know.

Thanks for the assistance!
