### ISSUE TITLE
Publish arranged Synonym Dictionary?

### ISSUE THREAD

**Issue by elsenchai** [Ziqing19/LabelPixivBookmarks#16]
I know this is not the correct place to post this. Can you publish some of the arraged Synonym Dictionary to Releases. I think this will greatly help new users

**Comment by Ziqing19** [comment]
Sorry for the late response.
It sounds a good idea for beginners. I will release a simple one in the next update.

**Comment by elsenchai** [comment]
thank

**Comment by Ziqing19** [comment]
I provided a simple dict sample in the new update. please check.
![image](https://github.com/Ziqing19/LabelPixivBookmarks/assets/44974769/58ea7865-ec09-484a-947c-d0c98672bf51)
