### ISSUE TITLE
能否实现给某作者的作品 自动添加 某个标签

### ISSUE THREAD

**Issue by baiheyyds** [Ziqing19/LabelPixivBookmarks#17]
大佬，能否实现给某作者的作品自动添加某个标签，比如有的作者的风格很固定，他的作品几乎都有某些元素，但是刚好他的tag又没有相关的描述，就需要自己手动分类了，所以我就在想能否给某作者的所有作品都打上某个标签

**Comment by Ziqing19** [comment]
emmm我感觉超过这个脚本能做的事情了
如果是希望对单个作者批量添加标签，我这边可以考虑把作者名也作为同义词词典识别的对象，这样在自动标签的时候可以自动给这个作者的所有作品打标签，然后再手动管理添加新的标签

**Comment by baiheyyds** [comment]
嗯，可以的，主要是看到搜索图片里边可以可以搜索作者所有作品，所以就想着能不能单独给某作者作品加某标签，如果整合到根据词典自动添加标签里面比较麻烦的话，感觉可以考虑单独放到其它功能里边，毕竟这只是一个很小众的功能

**Comment by Ziqing19** [comment]
抱歉更新的有点晚，现在在 高级设置 里选择使用作者名作为标签
然后在词典里添加对应的键值对就可以了，比如作者叫AA，希望给这个作者的作品自动添加Foo，Bar两个标签，那么就在词典里添加 Foo - AA    Bar - AA 两组键值对，这样识别的时候就会自动添加了

**Comment by baiheyyds** [comment]
辛苦大大了！牛的，这个功能太方便了，帮大忙了！

**Comment by baiheyyds** [comment]
辛苦大佬了，功能好用！
