### ISSUE TITLE
I keep getting the error "fail to fetch user tags"

### ISSUE THREAD

**Issue by crusty-man** [Ziqing19/LabelPixivBookmarks#2]
is there any way to fix it?

**Comment by lemako** [comment]
me too

**Comment by Ziqing19** [comment]
> is there any way to fix it?

Hi, can you please try to access this link directly?

https://www.pixiv.net/ajax/user/ + ${uid} + /illusts/bookmark/tags

Please replace the uid variable with your own uid.

This is the endpoint that pixiv website uses to fetch your tags information, and I have tried it only on my own accounts. It should return a JSON file including the tags.

**Comment by Ziqing19** [comment]
> me too

Hi, can you please try the link above? I would like to check what pixiv returns for your browser.

**Comment by lemako** [comment]
> > me too
> 
> Hi, can you please try the link above? I would like to check what pixiv returns for your browser.

{"error":true,"message":"\u62b1\u6b49\uff0c\u60a8\u5f53\u524d\u6240\u5bfb\u627e\u7684\u4e2a\u7528\u6237\u5df2\u7ecf\u79bb\u5f00\u4e86pixiv, \u6216\u8005\u8fd9ID\u4e0d\u5b58\u5728\u3002","body":[]}

如果是把 + ${uid} + 这一段全部替换的话就是这个 旁边的两个+号保留{"error":true,"message":"\u65e0\u6cd5\u627e\u5230\u60a8\u6240\u8bf7\u6c42\u7684\u9875\u9762","body":[]}

**Comment by Ziqing19** [comment]
> > > me too
> > 
> > 
> > Hi, can you please try the link above? I would like to check what pixiv returns for your browser.
> 
> {"error":true,"message":"\u62b1\u6b49\uff0c\u60a8\u5f53\u524d\u6240\u5bfb\u627e\u7684\u4e2a\u7528\u6237\u5df2\u7ecf\u79bb\u5f00\u4e86pixiv, \u6216\u8005\u8fd9ID\u4e0d\u5b58\u5728\u3002","body":[]}
> 
> 如果是把 + ${uid} + 这一段全部替换的话就是这个 旁边的两个+号保留{"error":true,"message":"\u65e0\u6cd5\u627e\u5230\u60a8\u6240\u8bf7\u6c42\u7684\u9875\u9762","body":[]}

这段解码出来是：抱歉，您当前所寻找的个用户已经离开了pixiv, 或者这ID不存在。
能确定手动输入的uid是正确的吗

**Comment by crusty-man** [comment]
It says I have too many bookmarks.
What's the limit of bookmarks?

**Comment by Ziqing19** [comment]
> It says I have too many bookmarks. What's the limit of bookmarks?
> Oh and I have 8 including uncategorised

I am not sure about the limit but I have 84 tags myself. Can you post the complete JSON file here?

**Comment by lemako** [comment]
> > > > me too
> > > 
> > > 
> > > Hi, can you please try the link above? I would like to check what pixiv returns for your browser.
> > 
> > 
> > {"error":true,"message":"\u62b1\u6b49\uff0c\u60a8\u5f53\u524d\u6240\u5bfb\u627e\u7684\u4e2a\u7528\u6237\u5df2\u7ecf\u79bb\u5f00\u4e86pixiv, \u6216\u8005\u8fd9ID\u4e0d\u5b58\u5728\u3002","body":[]}
> > 如果是把 + ${uid} + 这一段全部替换的话就是这个 旁边的两个+号保留{"error":true,"message":"\u65e0\u6cd5\u627e\u5230\u60a8\u6240\u8bf7\u6c42\u7684\u9875\u9762","body":[]}
> 
> 这段解码出来是：抱歉，您当前所寻找的个用户已经离开了pixiv, 或者这ID不存在。
> 能确定手动输入的uid是正确的吗

{"error":false,"message":"","body":{"public":[{"tag":"CG\u96c6","cnt":1},{"tag":"JK","cnt":1},{"tag":"NTR","cnt":4},{"tag":"P5","cnt":1},{"tag":"R-18","cnt":8},{"tag":"T\u30d0\u30c3\u30af","cnt":1},{"tag":"\u304a\u3063\u3071\u3044","cnt":1},{"tag":"\u304a\u306d\u30b7\u30e7\u30bf","cnt":2},{"tag":"\u304a\u5c3b","cnt":1},{"tag":"\u304f\u3071\u3041","cnt":1},{"tag":"\u3080\u3061\u3080\u3061","cnt":1},{"tag":"\u30a2\u30ba\u30fc\u30eb\u30ec\u30fc\u30f3","cnt":1},{"tag":"\u30a2\u30ba\u30fc\u30eb\u30ec\u30fc\u30f35000users\u5165\u308a","cnt":1},{"tag":"\u30a8\u30ed\u8863\u88c5","cnt":1},{"tag":"\u30aa\u30ea\u30b8\u30ca\u30eb","cnt":1},{"tag":"\u30af\u30a4\u30fc\u30f3\u30fb\u30a8\u30ea\u30b6\u30d9\u30b9(\u30a2\u30ba\u30fc\u30eb\u30ec\u30fc\u30f3)","cnt":1},{"tag":"\u30b9\u30d1\u30f3\u30ad\u30f3\u30b0","cnt":1},{"tag":"\u30d0\u7f8e\u8089","cnt":1},{"tag":"\u30d1\u30a4\u30ba\u30ea","cnt":1},{"tag":"\u30d7\u30ea\u30f3\u30c4\u30fb\u30aa\u30a4\u30b2\u30f3(\u30a2\u30ba\u30fc\u30eb\u30ec\u30fc\u30f3)","cnt":1},{"tag":"\u30da\u30eb\u30bd\u30ca1000users\u5165\u308a","cnt":1},{"tag":"\u30da\u30eb\u30bd\u30ca100users\u5165\u308a","cnt":1},{"tag":"\u30da\u30eb\u30bd\u30ca5","cnt":2},{"tag":"\u30da\u30eb\u30bd\u30ca\u30b7\u30ea\u30fc\u30ba","cnt":1},{"tag":"\u30da\u30eb\u30bd\u30ca\u30b7\u30ea\u30fc\u30ba\u30a4\u30e9\u30b3\u30f3","cnt":1},{"tag":"\u30de\u30b0\u30ed\u30ca","cnt":1},{"tag":"\u30de\u30de\u30b7\u30e7\u30bf","cnt":2},{"tag":"\u30e1\u30a4\u30c9","cnt":1},{"tag":"\u4e2d\u51fa\u3057","cnt":3},{"tag":"\u4e73\u98a8","cnt":1},{"tag":"\u4eba\u59bb","cnt":1},{"tag":"\u5236\u670d","cnt":1},{"tag":"\u5373\u5815\u30612\u30b3\u30de\u30b7\u30ea\u30fc\u30ba","cnt":1},{"tag":"\u539f\u521b","cnt":3},{"tag":"\u5973\u5b50\u9ad8\u751f","cnt":1},{"tag":"\u59c9\u306a\u308b\u3082\u306e","cnt":1},{"tag":"\u5c3b\u795e\u69d8","cnt":3},{"tag":"\u5de8\u4e73","cnt":2},{"tag":"\u6771\u90f7\u4e00\u4e8c\u4e09","cnt":1},{"tag":"\u6975\u4e0a\u306e\u4e73","cnt":1},{"tag":"\u6975\u4e0a\u306e\u5973\u4f53","cnt":1},{"tag":"\u6975\u4e0a\u306e\u8089","cnt":1},{"tag":"\u6b66\u898b\u5999","cnt":1},{"tag":"\u6bcd\u4e73","cnt":3},{"tag":"\u6bcd\u5b50\u76f8\u59e6","cnt":1},{"tag":"\u6d5c\u98a8","cnt":2},{"tag":"\u7206\u4e73","cnt":2},{"tag":"\u7fa9\u6bcd","cnt":1},{"tag":"\u8266\u3053\u308c","cnt":2},{"tag":"\u8266\u3053\u308c1000users\u5165\u308a","cnt":1},{"tag":"\u8266\u3053\u308c5000users\u5165\u308a","cnt":1},{"tag":"\u8266\u968a\u3053\u308c\u304f\u3057\u3087\u3093","cnt":2},{"tag":"\u843d\u9078","cnt":1},{"tag":"\u8fd1\u89aa\u76f8\u59e6","cnt":1},{"tag":"\u9006NTR","cnt":1},{"tag":"\u9670\u6bdb","cnt":2},{"tag":"\u9a0e\u4e57\u4f4d","cnt":1},{"tag":"\u9b45\u60d1\u306e\u8c37\u9593","cnt":3},{"tag":"\u9b54\u738b\u30de\u30b0\u30ed\u30ca","cnt":1},{"tag":"\u9e7f\u5cf6","cnt":2},{"tag":"\u672a\u5206\u985e","cnt":1834}],"private":[{"tag":"\u672a\u5206\u985e","cnt":111}],"tooManyBookmark":false,"tooManyBookmarkTags":false}}

昨天多了个空格

**Comment by Ziqing19** [comment]
> > > > > me too
> > > > 
> > > > 
> > > > Hi, can you please try the link above? I would like to check what pixiv returns for your browser.
> > > 
> > > 
> > > {"error":true,"message":"\u62b1\u6b49\uff0c\u60a8\u5f53\u524d\u6240\u5bfb\u627e\u7684\u4e2a\u7528\u6237\u5df2\u7ecf\u79bb\u5f00\u4e86pixiv, \u6216\u8005\u8fd9ID\u4e0d\u5b58\u5728\u3002","body":[]}
> > > 如果是把 + ${uid} + 这一段全部替换的话就是这个 旁边的两个+号保留{"error":true,"message":"\u65e0\u6cd5\u627e\u5230\u60a8\u6240\u8bf7\u6c42\u7684\u9875\u9762","body":[]}
> > 
> > 
> > 这段解码出来是：抱歉，您当前所寻找的个用户已经离开了pixiv, 或者这ID不存在。
> > 能确定手动输入的uid是正确的吗
> 
> {"error":false,"message":"","body":{"public":[{"tag":"CG\u96c6","cnt":1},{"tag":"JK","cnt":1},{"tag":"NTR","cnt":4},{"tag":"P5","cnt":1},{"tag":"R-18","cnt":8},{"tag":"T\u30d0\u30c3\u30af","cnt":1},{"tag":"\u304a\u3063\u3071\u3044","cnt":1},{"tag":"\u304a\u306d\u30b7\u30e7\u30bf","cnt":2},{"tag":"\u304a\u5c3b","cnt":1},{"tag":"\u304f\u3071\u3041","cnt":1},{"tag":"\u3080\u3061\u3080\u3061","cnt":1},{"tag":"\u30a2\u30ba\u30fc\u30eb\u30ec\u30fc\u30f3","cnt":1},{"tag":"\u30a2\u30ba\u30fc\u30eb\u30ec\u30fc\u30f35000users\u5165\u308a","cnt":1},{"tag":"\u30a8\u30ed\u8863\u88c5","cnt":1},{"tag":"\u30aa\u30ea\u30b8\u30ca\u30eb","cnt":1},{"tag":"\u30af\u30a4\u30fc\u30f3\u30fb\u30a8\u30ea\u30b6\u30d9\u30b9(\u30a2\u30ba\u30fc\u30eb\u30ec\u30fc\u30f3)","cnt":1},{"tag":"\u30b9\u30d1\u30f3\u30ad\u30f3\u30b0","cnt":1},{"tag":"\u30d0\u7f8e\u8089","cnt":1},{"tag":"\u30d1\u30a4\u30ba\u30ea","cnt":1},{"tag":"\u30d7\u30ea\u30f3\u30c4\u30fb\u30aa\u30a4\u30b2\u30f3(\u30a2\u30ba\u30fc\u30eb\u30ec\u30fc\u30f3)","cnt":1},{"tag":"\u30da\u30eb\u30bd\u30ca1000users\u5165\u308a","cnt":1},{"tag":"\u30da\u30eb\u30bd\u30ca100users\u5165\u308a","cnt":1},{"tag":"\u30da\u30eb\u30bd\u30ca5","cnt":2},{"tag":"\u30da\u30eb\u30bd\u30ca\u30b7\u30ea\u30fc\u30ba","cnt":1},{"tag":"\u30da\u30eb\u30bd\u30ca\u30b7\u30ea\u30fc\u30ba\u30a4\u30e9\u30b3\u30f3","cnt":1},{"tag":"\u30de\u30b0\u30ed\u30ca","cnt":1},{"tag":"\u30de\u30de\u30b7\u30e7\u30bf","cnt":2},{"tag":"\u30e1\u30a4\u30c9","cnt":1},{"tag":"\u4e2d\u51fa\u3057","cnt":3},{"tag":"\u4e73\u98a8","cnt":1},{"tag":"\u4eba\u59bb","cnt":1},{"tag":"\u5236\u670d","cnt":1},{"tag":"\u5373\u5815\u30612\u30b3\u30de\u30b7\u30ea\u30fc\u30ba","cnt":1},{"tag":"\u539f\u521b","cnt":3},{"tag":"\u5973\u5b50\u9ad8\u751f","cnt":1},{"tag":"\u59c9\u306a\u308b\u3082\u306e","cnt":1},{"tag":"\u5c3b\u795e\u69d8","cnt":3},{"tag":"\u5de8\u4e73","cnt":2},{"tag":"\u6771\u90f7\u4e00\u4e8c\u4e09","cnt":1},{"tag":"\u6975\u4e0a\u306e\u4e73","cnt":1},{"tag":"\u6975\u4e0a\u306e\u5973\u4f53","cnt":1},{"tag":"\u6975\u4e0a\u306e\u8089","cnt":1},{"tag":"\u6b66\u898b\u5999","cnt":1},{"tag":"\u6bcd\u4e73","cnt":3},{"tag":"\u6bcd\u5b50\u76f8\u59e6","cnt":1},{"tag":"\u6d5c\u98a8","cnt":2},{"tag":"\u7206\u4e73","cnt":2},{"tag":"\u7fa9\u6bcd","cnt":1},{"tag":"\u8266\u3053\u308c","cnt":2},{"tag":"\u8266\u3053\u308c1000users\u5165\u308a","cnt":1},{"tag":"\u8266\u3053\u308c5000users\u5165\u308a","cnt":1},{"tag":"\u8266\u968a\u3053\u308c\u304f\u3057\u3087\u3093","cnt":2},{"tag":"\u843d\u9078","cnt":1},{"tag":"\u8fd1\u89aa\u76f8\u59e6","cnt":1},{"tag":"\u9006NTR","cnt":1},{"tag":"\u9670\u6bdb","cnt":2},{"tag":"\u9a0e\u4e57\u4f4d","cnt":1},{"tag":"\u9b45\u60d1\u306e\u8c37\u9593","cnt":3},{"tag":"\u9b54\u738b\u30de\u30b0\u30ed\u30ca","cnt":1},{"tag":"\u9e7f\u5cf6","cnt":2},{"tag":"\u672a\u5206\u985e","cnt":1834}],"private":[{"tag":"\u672a\u5206\u985e","cnt":111}],"tooManyBookmark":false,"tooManyBookmarkTags":false}}
> 
> 昨天多了个空格

这个返回结果是正确的，但插件还是不能用是吗？也可能是解码的问题，我研究一下

**Comment by lemako** [comment]
The new version is working

**Comment by Ziqing19** [comment]
> The new version is working

cool
