### ISSUE TITLE
[BUG?] 使用的时候，似乎是因为咱的 Pixiv 账户里有几个坏档，所以很多时候无法进行下一步

### ISSUE THREAD

**Issue by AkiraChisaka** [Ziqing19/LabelPixivBookmarks#20]
**运行环境**
Windows 11 + Chrome + Tampermonkey

**如何复现**
1. 去到自己的收藏夹页面
2. 点击 ”Function“
3. 点击 “加载失效作品信息”
4. 加载的时候，最后会剩下几张无法加载，似乎是因为咱的 Pixiv 账号太老了，所以里面有一个坏了的档案，导致无法完成这一步
5. 因为这一步无法完成，所以也无法进行下一步，没法删掉别的没有损坏的失效作品了

**此前是否能够正常工作**
大概不能。咱今天下载了软件，成功用来批量删除了所有的作品标签。但是这个功能失效了。

**错误信息或截图**
![image](https://github.com/Ziqing19/LabelPixivBookmarks/assets/47231500/a9da6b4c-1e66-4136-b77b-c7c9b64ec691)
卡在最后这里了

**可能的修复方法**
咱感觉，如果有办法选择 “停止载入更多的内容，并根据目前已载入的内容执行下一步” 就好了。
因为，最后的这几个作品，似乎是彻底卡死在了咱的账号里的，完全删不掉。
所以手动告诉这个工具，“目前已经载入了所有有用的东西了，开始进行下一步吧” 应该就可以解决问题了。

**Comment by Ziqing19** [comment]
抱歉回复的有些晚，新版本增加了错误处理，应该不会卡住了
但可能最好还是弄清楚是什么问题，可以执行下下面的代码并把结果传过来吗？谢谢
```
const uid = "";  // 这里填上你的uid，地址栏里就有
const bookmarks = await (
  (await fetch("/ajax/user/"+uid+"/illusts/bookmarks?tag=&offset=20450&limit=100&rest=show")).json()
);
const a = document.createElement("a");
a.href = URL.createObjectURL(
  new Blob([JSON.stringify(bookmarks)], { type: "application/json" })
);
a.setAttribute("download", "bookmarks.json");
a.click();
```

**Comment by AkiraChisaka** [comment]
没问题！超感谢回复！

不过我之前已经把我的问题给 “搞好了”。

我试着用随机功能，随机从19000个收藏里选择99999张。虽然到最后的坏档处理不了，会卡主，但是只要手动停止的话，还是可以把剩下的图片随机选上的。

然后用随机功能的添加标签，给选上的作品加个标签。

这样最后在未分类里，就只剩下7个完全看不到的作品了！

然后把添加了标签的作品，再自动加载失效作品就可以了。之后删掉这个临时标签就好。

**Comment by AkiraChisaka** [comment]
> 抱歉回复的有些晚，新版本增加了错误处理，应该不会卡住了 但可能最好还是弄清楚是什么问题，可以执行下下面的代码并把结果传过来吗？谢谢

哼哼，这就是我最擅长的事情了！

没错！把互联网上来源不明的神秘代码直接复制到控制台和 Terminal 里！

试试就逝世！`sudo rm -rf` 都是吓小孩子的鬼故事，我不怕！

**Comment by AkiraChisaka** [comment]
平时没有打开控制台不知道……打开才吓一跳……

![image](https://github.com/Ziqing19/LabelPixivBookmarks/assets/47231500/ee2f92a2-9ee0-485f-8c65-a32a68d35080)

**Comment by AkiraChisaka** [comment]
忘记写 UID 了233

![image](https://github.com/Ziqing19/LabelPixivBookmarks/assets/47231500/2b3eb272-f2da-43a5-979a-3946c772346d)

[bookmarks.json](https://github.com/Ziqing19/LabelPixivBookmarks/files/14591345/bookmarks.json)

不过似乎还是不行，给了个 `net::ERR_BLOCKED_BY_CLIENT` 然后似乎只扒下来了一个作品的信息。

**Comment by AkiraChisaka** [comment]
在 `https://www.pixiv.net/en/` 的主界面又运行了一遍，这次不报错了

![image](https://github.com/Ziqing19/LabelPixivBookmarks/assets/47231500/2309faca-5248-4cd8-b619-9a175c9891de)

[bookmarks (2).json](https://github.com/Ziqing19/LabelPixivBookmarks/files/14591369/bookmarks.2.json)

**Comment by Ziqing19** [comment]
> 在 `https://www.pixiv.net/en/` 的主界面又运行了一遍，这次不报错了
> 
> ![image](https://private-user-images.githubusercontent.com/47231500/312560138-2309faca-5248-4cd8-b619-9a175c9891de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzM5NTUsIm5iZiI6MTcxMDM3MzY1NSwicGF0aCI6Ii80NzIzMTUwMC8zMTI1NjAxMzgtMjMwOWZhY2EtNTI0OC00Y2Q4LWI2MTktOWExNzVjOTg5MWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDIzNDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NGQ4NGNjZGEzNTJhYzg5NjQyMDYxNTVkZjBmYTczYzQ0NDk5Zjk4YTRjNGFjZTQxYjExMjllOWVlYTk0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T4-xpczRnADz_drb0hMDMfz-C7SEiPoY6qQDzJcZmVk)
> 
> [bookmarks (2).json](https://github.com/Ziqing19/LabelPixivBookmarks/files/14591369/bookmarks.2.json)

看了下应该是因为你已经处理完所有的未分类作品（包括那几个隐藏的bug作品），所以返回内容是空的
感觉这样能处理也行（捂脸

**Comment by kzcheng** [comment]
唔……感觉不像，因为记忆中，我在用那个奇怪的方法的时候，最后看到的是 “未分类” 里有7个作品，但是一个都显示不出来。

姑且现在我的问题已经解决了，所谓没问题啦！

Issue 可以 Close 了！

**Comment by AkiraChisaka** [comment]
唔……感觉不像，因为记忆中，我在用那个奇怪的方法的时候，最后看到的是 “未分类” 里有7个作品，但是一个都显示不出来。

姑且现在我的问题已经解决了，所谓没问题啦！

Issue 可以 Close 了！

**Comment by Ziqing19** [comment]
你现在在“未分类”下还会显示有7个作品吗？
如果还有的话可以再跑一次这个代码，上一次因为你已经贴好标签所以没获取到有bug的作品信息
```
const uid = "";  // 这里填上你的uid，地址栏里就有
const bookmarks = await (
  (await fetch("/ajax/user/"+uid+"/illusts/bookmarks?tag=&offset=0&limit=100&rest=show")).json()
);
const a = document.createElement("a");
a.href = URL.createObjectURL(
  new Blob([JSON.stringify(bookmarks)], { type: "application/json" })
);
a.setAttribute("download", "bookmarks.json");
a.click();
```

**Comment by kzcheng** [comment]
> 你现在在“未分类”下还会显示有7个作品吗？ 如果还有的话可以再跑一次这个代码，我改了下内容，上一次因为你已经贴好标签所以没获取到有bug的作品信息

不知道呢，我已经把所有的作品又放回未分类里了233

以后等我遇到问题的时候再说吧

**Comment by AkiraChisaka** [comment]
> 你现在在“未分类”下还会显示有7个作品吗？ 如果还有的话可以再跑一次这个代码，我改了下内容，上一次因为你已经贴好标签所以没获取到有bug的作品信息

不知道呢，我已经把所有的作品又放回未分类里了233

以后等我遇到问题的时候再说吧
