### ISSUE TITLE
Auto-Labeling Grabbing Tags From Each Pixiv Bookmark

### ISSUE THREAD

**Issue by KingKrouch** [Ziqing19/LabelPixivBookmarks#21]
Hi, so I was wondering if there were any plans to possibly update this script, so it can grab the tags used in the post, and automatically add them to your bookmark tags list? I noticed that there were already tags for R-18 works and AI illustrations, but I was wondering if there's a way that you can grab the tags for each post, and add those to the list as well. For example, if a Pixiv work had tags like "#ブルーアーカイブ" and "#小鳥遊ホシノ", to list some examples, those could be added as user tags, and the work in question will appear in those.

From what I can tell, the dictionary system would be useful for sorting tags that you definitely know exist, but the problem is when you have a massive amount of bookmarks, you're still currently stuck sorting them manually, which can be extremely time consuming.

**Comment by Ziqing19** [comment]
Hi! Sorry for the late response. If I am not misunderstanding, you would like all the tags that the author provided to be added in you user tags? I believe that there will be massive tags that does not help you manage your bookmarks.

**Comment by SADNESS81** [comment]
Hi. From what I've understood that you want to add tags to your bookmarks without having to manually add them, in this case you can turn on the option that lets you add the first tag if there's no match
You can actually do that by changing the logic of addFirst

`
if (!intersection.length && !prevTags.length) {
        if (addFirst === "true")
`

**Comment by KingKrouch** [comment]
> Hi! Sorry for the late response. If I am not misunderstanding, you would like all the tags that the author provided to be added in you user tags? I believe that there will be massive tags that does not help you manage your bookmarks.

Yeah, I'm aware that could potentially be a issue for some people, but I personally like to automate sorting my bookmarks using the tags they have, so I can quickly look for Pixiv works with a specific tag if I know on the top of my head what the work contained, much in the same way tags on Booru (image board) sites work.

**Comment by Ziqing19** [comment]
Surely I could add this function as an optional config but I am still thinking about if there is a better way to to it...
Does Pixiv has a filter for the tags that the works contain? Just like how we filter them by the user tags
Anyway I will update it this weekend

**Comment by Ziqing19** [comment]
Updated. Please comment if there's any problem or further requirement.

**Comment by KingKrouch** [comment]
Thanks, will give it a shot!

**Comment by KingKrouch** [comment]
> Updated. Please comment if there's any problem or further requirement.

So far, this seems to work how I expect. Thank you for this! It will be really helpful with sorting out my bookmarks! I should probably close this issue ticket now!
