### ISSUE TITLE
[BUG] Extension no longer works or loads in 

### ISSUE THREAD

**Issue by teaman1337** [Ziqing19/LabelPixivBookmarks#23]
**The Environments**
Windows 10 Home+Firefox+Tampermonkey+uBlock Origin(issue stays the same if uBlock is on or off) 

**To Reproduce**
I do not know, sorry I closed my browser after leaving my PC on overnight for it to sort and it started behaving this way. 

**Does it work before?**
Yes it did.

**Error Message or Screenshots**
![bugreport3](https://github.com/user-attachments/assets/6607256d-f93c-4853-824f-8d1b2ff5120d)
![bugreport1](https://github.com/user-attachments/assets/660094ae-30eb-49a7-bc18-090f90fbbe58)
![bugreport2](https://github.com/user-attachments/assets/a8c5b9b1-d36a-4e2c-a395-3d31cb6c4b58)
I am not proficient in coding at all, and don't know what this means, any help would be greatly appreciated, also I redacted/cropped out my user info sorry if that causes issues but I like being private.

**Comment by SADNESS81** [comment]
Hello.
The problem is due to some tags that has a special character (like % or #)
You might wanna check your tags if some of them has unusual characters. in this case remove the special character

**Comment by teaman1337** [comment]
> Hello. The problem is due to some tags that has a special character (like % or #) You might wanna check your tags if some of them has unusual characters. in this case remove the special character

It worked, thank you very much.
