### ISSUE TITLE
一些建议吧，希望能回一下啊

### ISSUE THREAD

**Issue by genmone** [Ziqing19/LabelPixivBookmarks#3]
第一能不能自定义一下标签类别，比如开始前设定把带有刻晴的图标签都加到刻晴分类里面，还有不要动已有的标签很累，最后麻烦我也想获得好的体验如果付费我也接收请大佬回复

**Comment by Ziqing19** [comment]
抱歉我刚看到，能再详细描述下问题吗？

推荐的使用方法是，在第一次使用前先收藏 #刻晴 标签，之后其他所有选择范围内的图（例如未分类）中含有 #刻晴 标签的图都会被加入你自己的“刻晴”收藏夹。

默认情况下已有的标签是不会被修改的，我没有太明白是什么意思，能再讲清楚一点吗？

**Comment by genmone** [comment]
大佬是这样的有的使用的是两次，第一次做了很多细分，比如原神刻晴，原神甘雨，碧蓝航线赤诚等等，但是同时也有碧蓝航线，原神等大类，第一次使用过后原神刻晴标签中的图片少了许多，加入到了原神标签中，同时，如原神胡桃，原神琴这类标签却没有了，第二次我的标签里新加了类别赛马娘，但是分类过后其中图片没有变化，其余有赛马娘（官方分类）的图片没有加入进来。同时原神，碧蓝航线等大类有出现了有图片未被收录的状况。（两次均为全部作品）
所以我觉得能不能加一个功能就是自定义一下比如我的收藏标签中有原神标签吗，分类是自定义 一下把官服带某一个标签的图片主动分到预先设置好的类别中。
我是计科院的学生，也知道这方面确实困难，希望大佬能有解决方法，我也愿意帮忙，不过我是fw就是了

**Comment by genmone** [comment]
第一我自己做了细分，但是分类后，一部分标签都没有

**Comment by Ziqing19** [comment]
ok我明白了

这个脚本本质是对图片“自带的tag”和“你收藏的tag”取交集然后提交。如果出现原本分好类的却被移除说明这张图“自带的tag”和你“之前分到的tag”没有交集，例如可能自带tag是日文，而你的tag是中文。

那下个版本我可以尝试提供新选项“是否覆盖图片原来收藏的tag”，来选择是追加还是替换图片本身的分类。

另外一个你说的应该是提供同义词词库，这个主要是不方便保存，我之后有空想想怎么实现。上面说的功能我会尽快更新的。

**Comment by genmone** [comment]
期待中，其实大佬的脚本算是比较精致了，建议收费赚点奶茶钱，希望我毕业后也能像大佬一样

**Comment by Ziqing19** [comment]
刚更新了新版本，如果有与之相关的问题可以继续在这个issue下提交，暂时不会关

**Comment by genmone** [comment]
大佬，使用是直接点击同义词典吗，为啥我点不开啊

**Comment by Ziqing19** [comment]
> 大佬，使用是直接点击同义词典吗，为啥我点不开啊

点不开可能是因为浏览器不支持，chrome/firefox/edge都是可以的
