### ISSUE TITLE
网页上找不到“自动添加标签”按钮

### ISSUE THREAD

**Issue by AutumnNight69** [Ziqing19/LabelPixivBookmarks#5]

**Comment by Ziqing19** [comment]
请问是用的最新的4.4版吗，今天之前可以正常使用吗，请多提供一些信息方便我找到问题

**Comment by AutumnNight69** [comment]
?最新的不是4.5吗

**Comment by Ziqing19** [comment]
啊记错了，之前可以用吗，有尝试刷新几次吗

**Comment by AutumnNight69** [comment]
刷新过了没用QAQ 之前没用过QAQ

**Comment by Ziqing19** [comment]
f12看下console有什么报错吗，最好截图一下

**Comment by Ziqing19** [comment]
如果使用没问题的话，一天后将关闭这个issue

**Comment by AutumnNight69** [comment]
![97G7V9@3NE48 B7M0)GNC O](https://user-images.githubusercontent.com/77198268/144693290-fbe696d5-b9c1-42e8-a4bc-20fa9e1925cd.png)

**Comment by Ziqing19** [comment]
console里似乎还有其他的报错，是使用了别的什么插件吗？可能会有部分冲突。
报错的部分是找不到页面上某个元素，在这里指的是收藏页面的用户封面部分，包括头像、底图的那块元素。
我不确定是不是不同用户的UI是不一样的？？总之刚刚发布了4.6版，提供了无法获取用户信息时的一些备用手段，如果还是无法成功注入请继续留言。
