### ISSUE TITLE
Label Button no logner appearing on bookmarks page

### ISSUE THREAD

**Issue by Gilgamesh0028** [Ziqing19/LabelPixivBookmarks#6]
Followed all instructions, could not get LABEL to appear anywhere.

**Comment by Ziqing19** [comment]
Hi. I just checked and it still works properly in my browser.
Could you please provide more information? What is your browser? Is there any error message in the console?

**Comment by Gilgamesh0028** [comment]
Firefox version 96.0, here is a screenshot of the console when I just load ./bookmarks/artworks
uBlock Origin is installed, and is up to date. 
Would prefer to have a solution that does not involved me needing to disable adblock, but I understand if it is needed.

![image](https://user-images.githubusercontent.com/98428877/152669027-6a8ffc0e-950f-4d83-b9eb-10adc38222ad.png)

**Comment by Ziqing19** [comment]
I didn't see any error message from the script. I think it must have something to do with the adblock. Maybe some dom elements were removed leading to lack of user information, so that the script failed to initiate.
I would like to try uBlock Origin myself and figure out how happened. It might take some time and I will inform you if I fix it.

**Comment by Ziqing19** [comment]
![image](https://user-images.githubusercontent.com/44974769/152671779-b2c0cd75-a64b-4ca1-b1a3-b14ec5437b36.png)
It seems that the script still works on uBlock Origin and Firefox 96...Any other clues?

The script will print `[Label Bookmarks] Injected` in the console if it loads succecssfully.

**Comment by Gilgamesh0028** [comment]
here is the full output of the console, with and without ublock origin enabled
without ublock:
![image](https://user-images.githubusercontent.com/98428877/152696094-fe9805af-ad41-45c5-bd4e-114ebdf30ba4.png)


with ublock:
![image](https://user-images.githubusercontent.com/98428877/152696131-2f06b55b-acfb-49be-9c3a-8b34fbe9b55e.png)

**Comment by Ziqing19** [comment]
It seems the script is not even loaded. Neither printing injection message nor error message.
You might set the DEBUG variable in 338 line to be true, and reload the page. It should display information of your account like your ID, your bookmarked tags.
![image](https://user-images.githubusercontent.com/44974769/152709728-99b40c8c-ce34-47a1-8b50-8fb45610e10e.png)

If it still makes no difference, I think the script is not even loaded. Are the tampermonkey scripts other than this one running well on firefox?

**Comment by Gilgamesh0028** [comment]
AHA! It was installed in a disabled state. Now I'm seeing some errors related to the script.
(with ublock enabled)
![image](https://user-images.githubusercontent.com/98428877/152720155-fe597784-8105-4841-9aaa-a91ec448b398.png)
(with ublock disabled)
![image](https://user-images.githubusercontent.com/98428877/152720214-102d85a9-dc75-49b9-b9d8-37cfd8c55297.png)

**Comment by Ziqing19** [comment]
Sorry for the late response. I found the GreaseMonkey extension might be the cause when I tried to reproduce the bug.
Please try Tampermonkey at https://www.tampermonkey.net/, the extension that I am developing based on. And I think there are some mismatches between the script and GreaseMonkey. I will manage to fix them ASAP.

**Comment by Gilgamesh0028** [comment]
AHA! It works! I am unsure as to *why* it works now, but it appears tampermonkey vs greasemonkey causes certain issues. 

Thanks for all your help!
