### ISSUE TITLE
删除标签功能无法正常使用

### ISSUE THREAD

**Issue by bbdan0013** [Ziqing19/LabelPixivBookmarks#7]
包含图片数量较少的标签可以正常删除，数量较多的标签显示删除成功但是并没有删除

**Comment by Ziqing19** [comment]
了解，可能是一次性需要删除的标签数量超过了接口限制，将会尽快修复

**Comment by bbdan0013** [comment]
超过了10个，大概有一个标签下有几百个，不知道是不是有可能是因为标签中有被删除的作品

**Comment by Ziqing19** [comment]
我确认下“删除标签”是指删除一个标签下所有的作品，还是清除一个作品下收藏的标签
我好像理解反了

**Comment by Ziqing19** [comment]
已修复
