### ISSUE TITLE
Script fails to delete tags in private bookmarks

### ISSUE THREAD

**Issue by piticurus** [Ziqing19/LabelPixivBookmarks#8]
Trying to delete tags from private bookmarks results in the prompt appearing as usual, but scanning 0 works.
I tried changing the publication type for labeling in advanced, but it does nothing, i think it's a bug.
(great feature by the way, even if a little hidden)

**Comment by Ziqing19** [comment]
Thank you for your information. I think I might have forgotten some testing works for private bookmarks.
I would try to fix that ASAP!

**Comment by Ziqing19** [comment]
Fixed. Please comment if there is still any other problem.

**Comment by piticurus** [comment]
The only other thing that comes to mind could be implementing a dark theme, but no other technical problems.

**Comment by Ziqing19** [comment]
I have posted a new version which follows the website theme.  Try it out

**Comment by piticurus** [comment]
ok good, I don't have anything else to report for now, thanks for the work
