### ISSUE TITLE
Excluding tags 

### ISSUE THREAD

**Issue by SADNESS81** [Ziqing19/LabelPixivBookmarks#9]
Wouldn't it be helpful if you could exclude tags through Synonyms because it takes too long for labeling artwork that has "オリジナル" on it

**Comment by Ziqing19** [comment]
It seems that you already bookmarked the tag "オリジナル" so that the script will label artworks with this tag.
I would suggest you to remove the whole "オリジナル "tag, but if you want to manage it manually I will make an exclude tag pool for that.

**Comment by SADNESS81** [comment]
> I would suggest you to remove the whole "オリジナル "tag
it's more like I want to separate things and I use the first tag option so I can see which tag I didn't add to the Synonyms and that's why

**Comment by Ziqing19** [comment]
I see. I would make an exclusion pool where tags will be ignored

**Comment by Ziqing19** [comment]
I have posted a new version with the exclusion pool located in the advanced settings. Inform me if it is not working properly

**Comment by SADNESS81** [comment]
> I have posted a new version with the exclusion pool located in the advanced settings. Inform me if it is not working properly

It does work correctly but is it possible to get it to work with the "Whether the first tag will be added if there is not any match" option? 
like if there's an ignored tag let it add the 2nd tag instead, I don't know if it is possible though

**Comment by Ziqing19** [comment]
Yeah that sounds reasonable. I will make an update soon

**Comment by Ziqing19** [comment]
updated now

**Comment by SADNESS81** [comment]
It works perfectly fine, but it may be a good idea to have a limit when creating a tag, for example, if the tag has less than 10 bookmarked artwork it'll remain uncategorized, it helps with organizing

**Comment by SADNESS81** [comment]
or maybe if it's easier for you I suggest adding an option to remove tags in the function page

**Comment by Ziqing19** [comment]
In my opinion, I prefer display the number of bookmarked works of a tag after the tag name to help you delete those that you don't want. Limiting the number when creating a tag would make the logic more complicated, and users will get confused.
To remove a tag, you can select the tag and click Delete This Tag button in the function page, which has been implemented in the last version.

**Comment by SADNESS81** [comment]
> In my opinion, I prefer display the number of bookmarked works of a tag after the tag name to help you delete those that you don't want

Yeah that will do, thank you so much for adding these features
